site_name: pyramid-capstone
repo_url: https://github.com/tomascorrea/pyramid-capstone
site_url: https://tomascorrea.github.io/pyramid-capstone
site_description: FastAPI-like decorators for Pyramid - Build type-safe REST APIs with automatic validation, serialization, and OpenAPI documentation.
site_author: Tomas Correa
edit_uri: edit/main/docs/
repo_name: tomascorrea/pyramid-capstone
copyright: Maintained by <a href="https://github.com/tomascorrea">Tomas Correa</a>.

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Tutorial: tutorial.md
  - Security: security.md
  - API Reference: modules.md
  - Examples: examples.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomascorrea/pyramid-capstone
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyramid-capstone

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html