[tool.poetry]
name = "pyramid_capstone"
version = "0.1.0"
description = "FastAPI-like decorators for Pyramid - Build type-safe REST APIs with automatic validation, serialization, and OpenAPI documentation."
authors = ["Robbin dev team <fdev@robbin.com.br>"]
repository = "https://github.com/tomas_correa/pyramid-capstone"
documentation = "https://tomas_correa.github.io/pyramid-capstone/"
readme = "README.md"
packages = [
  {include = "pyramid_capstone"}
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pyramid = "^2.0"
cornice = "^6.0"
marshmallow = "^3.19"
venusian = "^3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.6.4"
mypy = "^0.981"
pre-commit = "^2.20.0"
tox = "^3.25.1"
webtest = "^3.0.0"
waitress = "^3.0.0"
pycornmarsh = "*"
mkdocs-material = "^9.6.18"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocstrings = "^0.29.1"
mkdocstrings-python = "^1.16.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37']
preview = true

[tool.mypy]
files = ["pyramid_capstone"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"

[tool.ruff]
target-version = "py37"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
    # Function is too complex (for now, we'll address complexity later)
    "C901",
    # Consider else block (stylistic preference)
    "TRY300",
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "A002", "A003"]  # Allow shadowing builtins in tests
"examples/*" = ["A003"]  # Allow shadowing builtins in examples (common for id fields)
"*/conftest.py" = ["B018"]  # Allow useless expressions in conftest

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["pyramid_capstone"]


